# Generated by Django 3.2.13 on 2022-07-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='uploaded_image',
        ),
    ]
