# Generated by Django 3.2.13 on 2022-07-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_picture_uploaded_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='picture',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='picture',
            name='birthday',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='picture',
            name='comment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='picture',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='picture',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
