# Generated by Django 3.2.13 on 2022-07-25 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20220725_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='raw'),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
