# Generated by Django 3.2.13 on 2022-07-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220725_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='uploaded_image',
        ),
    ]
