# Generated by Django 3.2.13 on 2022-07-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220726_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
